### ISSUE TITLE
this not an issue it just a question

### ISSUE THREAD

**Issue by vincentroman** [yTakkar/React-Instagram-Clone-2.0#29]
please is this program responsive on any device? plus does it have the same features as the php version?

**Comment by yTakkar** [comment]
No it's not responsive.
PHP version has more features extra like uploading different types of media (video, audio, documents, location & link) & group conversation.
But I'll suggest not to use PHP version of Instagram-Clone because of these reasons:

-  very slow
- code is badly structured and organized. (I developed PHP version when I was a beginner in web development)
- Bit difficult to setup
- Not reactive
- old-school JS code
- **most importantly (NOT MAINTAINED)**
- and many more..
